# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines bellow are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - main: ./cmd/tekton.go
    binary: tekton
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .Binary }}-{{- title .Os }}-{{- .Arch }}-{{- .Version }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
